"""empty message

Revision ID: c0ba03bd41ee
Revises: b8920f9110db
Create Date: 2026-03-11 14:52:35.841114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0ba03bd41ee'
down_revision = 'b8920f9110db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=255), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
